data <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=FALSE, sep=';')
data$V2<- strptime(paste(data$V1,data$V2), "%d/%m/%Y %H:%M:%S")
png(filename='plot4.png', width=480, height=480)
par(mfrow = c(2, 2))
plot(data$V2, data$V3, type='l', xlab='', ylab='Global Active Power')
plot(data$V2, data$V5, type='l', xlab='datetime', ylab='Voltage')
plot(data$V2, data$V7, type='l', xlab='', col='black', ylab='energy sub metering')
lines(data$V2, data$V8, col='red')
lines(data$V2, data$V9, col='blue')
legend("topright",  bty = "n", lty=c(1,1), col = c("black", "blue", "red"), c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$V2, data$V4, type='l', xlab='datetime', ylab='global_reactive_power')
dev.off()